### ISSUE TITLE
Speed up part of video

### ISSUE THREAD

**Issue by trongtrong** [deepmedia/Transcoder#101]
thank you for great libary,  as title, Is it possible to only apply the speedup in certain regions in the video. Eg. from 10 to 15 seconds and again from 50 to 60 seconds?

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Yes, with a custom TimeInterpolator. See SpeedTimeInterpolator and adapt it to your scenario.
