### ISSUE TITLE
Gettrackformat returned null for 1/3 sources error

### ISSUE THREAD

**Issue by pawaom** [deepmedia/Transcoder#114]
Gettrackformat returned null for 1/3 sources error

I am trying to merge 3 videos 
1 is a Mkv file
2 is a 3gp file
3 is avi file

merging the 3gp and mkv worked well., but when i tried to add avi file it gave me the error Gettrackformat returned null for 1/3 sources  how can we solve this issue is there an alternative

Individually the files worked well and were converted.

**Comment by natario1** [comment]
Looks like one of them does not have a video/audio track
