### ISSUE TITLE
How can we add filters to the videos 

### ISSUE THREAD

**Issue by pawaom** [deepmedia/Transcoder#121]
How can we add filters to the videos 

Can we add Filters like these

https://github.com/MasayukiSuda/GPUVideo-android

If yes how can we do it.

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

We don't plan to support filters for now, sorry.
