### ISSUE TITLE
Can we keep Original Audio of Video and overlay second audio over it.

### ISSUE THREAD

**Issue by pawaom** [deepmedia/Transcoder#123]
Can we keep Original Audio of Video and overlay second audio over it?

And can we add multiple audio over same video Like say Original Audio from video and Song 1 and Song 2 overlayed over it simultaneously. like both video's audio and both songs play at the same time.

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

We don't plan to support audio blending, sorry.
