### ISSUE TITLE
buffers.getoutputbuffer(result) must not be null error for updated version 0.10.0 

### ISSUE THREAD

**Issue by pawaom** [deepmedia/Transcoder#126]
buffers.getoutputbuffer(result) must not be null error for updated version 0.10.0 (new kotlin version)

When we try to use the updated version it gives above error ,for all the videos.

Earlier version (Java) used to work.

**Comment by vanniktech** [comment]
Got a repro for this here: https://github.com/natario1/Transcoder/issues/184

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Tracking in #184
