### ISSUE TITLE
NullPointerException android.media.MediaExtractor.release()

### ISSUE THREAD

**Issue by changyoutianxia** [deepmedia/Transcoder#148]
![image](https://user-images.githubusercontent.com/46896358/128703817-29317a17-bf96-4d33-bd1d-17c0a54488fa.png)
![image](https://user-images.githubusercontent.com/46896358/128703838-8b43e42c-464e-47a4-97c7-360f8cdb038a.png)

**Comment by natario1** [comment]
Can you try with 0.10.4 and check if this is still an issue?

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Closing assuming it's fixed in latest version, feel free to add more info if not.
