### ISSUE TITLE
Does not transcode when setSpeed(0.5F) or less 1

### ISSUE THREAD

**Issue by VitalySizov** [deepmedia/Transcoder#176]
This issue can be reproduced in a demo application

**Comment by preqel** [comment]
i have the same issue when set Speed less than 1

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Hi, speed < 1 seems to work for me. If you have problem with a specific video, please attach it.
