### ISSUE TITLE
BufferOverflowException (ref #163) #164 is not fixed in implementation 'com.github.jumperson:transcoder:0.10.4.2'

### ISSUE THREAD

**Issue by shoaibspringr** [deepmedia/Transcoder#187]
BufferOverflowException (ref #163) #164 is not fixed in implementation 'com.github.jumperson:transcoder:0.10.4.2'

**Comment by licaon-kter** [comment]
@shoaibspringr not in 0.10.5 either? https://natario1.github.io/Transcoder/about/changelog

**Comment by natario1** [comment]
#163 is still open so I'm closing this.
