### ISSUE TITLE
Trim and Merge issue

### ISSUE THREAD

**Issue by AsynctaskCoffee** [deepmedia/Transcoder#189]
When I trim and merge multiple videos I can see there are some glitches from output video (on video switches). 

I am using

`   private lateinit var builder: TranscoderOptions.Builder
    private var mTranscodeVideoStrategy: TrackStrategy? = null

    private var mTranscodeOutputFile: File? = null

    init {
        mTranscodeVideoStrategy = DefaultVideoStrategy.Builder()
            .addResizer(MyExactResizer(1080, 1920))
            .frameRate(30)
            .build()
    }

    fun setVideos(
        mTranscodeOutputFile: File?,
        videoList: ArrayList<AnalyzeResult>,
        context: Context,
        musicPath: String?
    ) {
        this.mTranscodeOutputFile = mTranscodeOutputFile
        builder = Transcoder.into(mTranscodeOutputFile!!.absolutePath)
        videoList.forEach {
            val start: Long = (max(0, it.startMs!!) * 1000).toLong()
            val end: Long = (max(0, it.duration!! + it.startMs!!) * 1000).toLong()
            builder.addDataSource(
                TrackType.VIDEO,
                ClipDataSource(
                    UriDataSource(context, Uri.parse(it.mediaPath)),
                    start,
                    end
                )
            )
        }
        musicPath?.let {
            builder.addDataSource(TrackType.AUDIO, context, Uri.parse(it))
        }
    }

    fun processVideo(transcoderListener: TranscoderListener) {
        builder
            .setListener(transcoderListener)
            .setVideoTrackStrategy(mTranscodeVideoStrategy)
            .transcode()
    }`
    
    
    
Any recommendations ?

**Comment by natario1** [comment]
I'm not sure there's anything wrong with the library here. Given that I'm answering many months late and you have probably moved on, I'm going to close this, but if you still struggle with these please provide more info (for example, two input videos and the transcoded video with the glitch)
