### ISSUE TITLE
Error when concat multipe audio

### ISSUE THREAD

**Issue by thinhkaku** [deepmedia/Transcoder#40]
Transcoder.into(path!!)
            .addDataSource(pathAudio1) // or...
            .addDataSource(pathAudio2) // or...
            .setListener(object : TranscoderListener {
                override fun onTranscodeCompleted(successCode: Int) {
                    Log.d("Process: ", "onTranscodeCompleted")
                }

                override fun onTranscodeProgress(progress: Double) {
                    Log.d("Process: ", "${progress}")
                }

                override fun onTranscodeCanceled() {
                    Log.d("Process: ", "onTranscodeCanceled")
                }

                override fun onTranscodeFailed(exception: Throwable) {
                    Log.d("Process: ", "onTranscodeFailed ${exception.message}")
                }

            }).transcode()

Result message:
onTranscodeFailed: More than one source selected for type VIDEO, but getTrackFormat returned null.

**Comment by keithbrianptomo** [comment]
?

**Comment by natario1** [comment]
Thanks for reporting. If you know it's audio, you can use `addDataSource(TrackType.AUDIO, data)` for now.

**Comment by natario1** [comment]
(Note: it's been a long time since my last issues review. I am sorry about the delay and I know you have moved on by now. Still, I'm going to answer where I can)

This should be fixed in latest version.
