### ISSUE TITLE
trim not working exactly

### ISSUE THREAD

**Issue by Maulik61** [deepmedia/Transcoder#65]
Like i trim for 0 to 60 second and after trim a video i got the video having 0 to 69 seconds.
so not accurate.

If you find any answer let me know. 
I am also working on this issue.

**Comment by natario1** [comment]
We only trim up to video sync frames right now. If your video has very few sync frames trim will be inaccurate

**Comment by Maulik61** [comment]
I got your points.
Thanks 
I f 
 
  On Wed, 4 Mar 2020 at 7:29 PM, Mattia Iavarone<notifications@github.com> wrote:   
We only trim up to video sync frames right now. If your video has very few sync frames trim will be inaccurate
