### ISSUE TITLE
Reduce compression time

### ISSUE THREAD

**Issue by ritesh-karmare** [deepmedia/Transcoder#71]
Device: Nokia 5
Library version - 0.9.0

Video1: 3:42 mins, 552 MB
Video2: 4 mins, 17 MB
Video3: 2 mins, 13 MB

@natario1  _The compression for the video file is working great._ 
However, all videos, individually, are taking a minimum of 3 mins for compression to complete.

**Here's the code I am using for compression:**

```
 public static DefaultVideoStrategy for360x480() {
        return DefaultVideoStrategy.exact(360, 480)
                .bitRate(500L * 1000)
                .frameRate(20)
                .keyFrameInterval(2F)
                .build();
    }
```

```
 mTranscodeAudioStrategy = DefaultAudioStrategy.builder()
                .channels(1)
                .bitRate(16000)
                .build();
```

        Transcoder.into(destPath)
                .addDataSource(filePath) // or...
                .setAudioTrackStrategy(mTranscodeAudioStrategy)
                .setVideoTrackStrategy(DefaultVideoStrategies.for360x480())
                .setListener(new TranscoderListener() {
                    public void onTranscodeProgress(double progress) {
                        Log.i(TAG, "onTranscodeProgress: "+progress);
                    }
                    public void onTranscodeCompleted(int successCode) {
                        Log.i(TAG, "onTranscodeCompleted: "+successCode);
                    }
                    public void onTranscodeCanceled() {
                        Log.i(TAG, "onTranscodeCanceled: ");
                    }
                    public void onTranscodeFailed(@NonNull Throwable exception) {
                        exception.printStackTrace();
                    }
                }).transcode();

**Comment by natario1** [comment]
Should be better after #202 .
