### ISSUE TITLE
Input channel count (6) not supported

### ISSUE THREAD

**Issue by tomaz** [deepmedia/Transcoder#84]
Particular reason for this limitation?

If I comment out `AudioEngine.java` lines 85-87 and use output channel count of 2, transcoding occurs just fine. Would pull request with removed check be acceptable? Alternatively, removal of this check may be optional, opt-in via `AudioStrategy` parameters for example...

**Comment by natario1** [comment]
(Note: it's been a long time since my last issues review. I am sorry about the delay and I know you have moved on by now. Still, I'm going to answer where I can)

No particular reason, just increased complexity in the audio algorithms. Tracking this in #75
